# Generated by Django 4.1 on 2023-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Сөз')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Түсіндірме')),
                ('url_youtube', models.CharField(max_length=255, verbose_name='Сілтеме')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Сөздік',
                'verbose_name_plural': 'Сөздіктер',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тегі')),
                ('message', models.TextField(verbose_name='Хабарлама мәтіні')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Келген күні')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
    ]
