# Generated by Django 4.1 on 2023-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_remove_question_last_name_question_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='url_youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сілтеме'),
        ),
    ]
