# Generated by Django 4.1 on 2023-04-04 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_dictionary_url_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тегі')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон номері')),
                ('status_admin', models.BooleanField(default=False, verbose_name='Админ статусы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жүйе қолданушы',
                'verbose_name_plural': 'Жүйе қолданушы',
            },
        ),
    ]
